version: '3.8'
services:
  mongo-test:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: test
    ports:
      - 27019:27017
    volumes:
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  pg-test:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5434:5432'
    volumes:
      - pg:/var/lib/postgresql/data
volumes:
  pg:
    driver: local
