name: Setup monorepo
description: Sets up the repository
runs:
  using: composite
  steps:
    - name: 🏗 Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 7

    - name: 🏗 Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 16
        chace: 'pnpm'
        cache-dependency-path: 'pnpm-lock.yaml'

    - name: ♻️ Restore node_modules cache
      uses: actions/cache@v2
      with:
      path: '**/node_modules'
      key: ${{ runner.os }}-modules-${{ hashFiles('pnpm-lock.yaml') }}

    - name: 📦 Install dependencies
      shell: bash
      run: pnpm install --prefer-offline --frozen-lockfile
